"""empty message

Revision ID: 77efd981bd3e
Revises: 3bd6f002281c
Create Date: 2017-02-24 07:26:05.966106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77efd981bd3e'
down_revision = '3bd6f002281c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items', 'bucketlist_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint(None, 'users', ['username'])
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('items', 'bucketlist_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
